### ISSUE TITLE
edges don't appear

### ISSUE THREAD

**Issue by jaredmcqueen** [Brenden-Morales/ThreeForce#1]
I see you've written some code to show/hide edges using lowercase L.  By default they should be turned on, but I don't see them.  I'm trying to debug your code to see edges between nodes -- have you got this working or is it a WIP?

excellent examples btw, learning GPGPU methods to do force directed graphs like you and stumbled upon your project.  I hope to help out any way I can.

**Comment by Brenden-Morales** [comment]
Ah, that's because there _are no edges_ in the current implementation. I've just got a bunch of nodes that aren't related to eachother. If you checkout from this commit:

https://github.com/Brenden-Morales/ThreeForce/commit/b0c02ed4f276448cb7002096cf383d7c9cfe1897

you should see edges functioning like you're looking for.

Or, in main.js copy in this code for the node creation function

```
for(var i = 1; i <= 500; i ++){
    nodes[i-1].push(i);
    nodes.push([]);
}
```

this just creates a simple "chain"

**Comment by jaredmcqueen** [comment]
ok great!  yep -- works great.  This is really fantastic work btw.  I'm working on a force-directed project that could _really_ benefit from GPGPU parallelism.  Excited to how this project will shape up.  I'll def submit pull requests as I digest and start to build on what you have here :+1:
